source 'http://rubygems.org'

gem 'rails', '3.2.10'
gem 'activerecord-jdbcpostgresql-adapter'

gem 'jruby-openssl'

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'therubyrhino'
  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'

gem 'jruby_mahout'

gem 'devise'