source 'http://rubygems.org'

gem 'rails', '3.2.10'
gem 'activerecord-jdbcpostgresql-adapter'

gem 'jruby-openssl'

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'therubyrhino'
  gem 'uglifier', '>= 1.0.3'
end

gem 'jruby_mahout', :path => "../../jruby_mahout"

gem 'devise'

gem 'jquery-rails'
gem 'haml-rails'
gem 'anjlab-bootstrap-rails', '>= 2.2', :require => 'bootstrap-rails'